# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

PUBLISH_FROM_BRANCH = $(shell git branch --show-current)
DEBUG_PUBLISH = 0
.PHONY: publish
publish:
ifeq ($(DEBUG_PUBLISH),1)
	bash -x ./publish.sh "$(PUBLISH_FROM_BRANCH)"
else
	bash ./publish.sh "$(PUBLISH_FROM_BRANCH)"
endif